version: "3.3"
# https://thomasgouveia.fr/blog/containerize-next-js.html

services:
  soj-frontend:
    ports:
      - 3000:3000
    build:
      context: packages/landingpage
      dockerfile: Dockerfile
    volumes:
      - ./packages/landingpage:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next