version: "3"

services:
  nk_client:
    container_name: nk_client
    image: nick3141/nickkelly.dev-frontend:latest
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - nk

networks:
  nk:
    driver: bridge
