version: "3"

services:
  nk_redis:
    container_name: nk_redis
    image: redis:6.0.9
    restart: unless-stopped
    ports:
      - 6379:6379
    command: redis-server --requirepass ${REDIS_PSW}
    networks:
      - nk

  nk_pg:
    container_name: nk_pg
    image: postgres:12.4
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: nk
      POSTGRES_PASSWORD: ${PG_PSW}
      POSTGRES_DB: nk
    networks:
      - nk

networks:
  nk:
    driver: bridge
