#!/usr/bin/env sh

echo "pulling source code..."
git pull

echo "installing api packages..."
cd ../api;
npm install;

echo "installing cms packages..."
cd ../cms;
npm install;

echo "installing client packages..."
cd ../client;
npm install;
